"""
Per-honeypot × per-iter breach-count heatmap.

Answers supervisor Q1: "Is it the same honeypots?" → Yes. The heatmap reveals
that per-iter breach composition is stable across iters 0..7 — the ceiling is
a property of the target set (PII-dominant phone+email = 48.7% of all hits),
not of any particular checkpoint pair.

Source: figures/honeypot_tiers.json::honeypots[*].per_iter_hits
(generated by util/honeypot_difficulty.py from canonical cross_eval).

CLI:
    python plotting/plot_honeypot_per_iter_heatmap.py \\
        --results results-<ID>[:Label] [--out-dir figures/]
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np

try:
    from ._data import apply_paper_style, parse_results_arg
except ImportError:
    sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
    from plotting._data import apply_paper_style, parse_results_arg

apply_paper_style()

DESCRIPTION = "Per-honeypot per-iter breach-count heatmap (composition stability across iters)"

TIER_ORDER = ["pii_dominant", "harvestable", "rare"]
TIER_LABELS = {
    "pii_dominant": "PII-dominant",
    "harvestable": "Harvestable",
    "rare": "Rare",
}
TIER_BG_COLORS = {
    "pii_dominant": "#FFEBEE",
    "harvestable": "#FFF3E0",
    "rare": "#ECEFF1",
}


def _load_tiers(selfplay_dir: str) -> dict | None:
    candidates = [
        Path(selfplay_dir).parent / "figures" / "honeypot_tiers.json",
        Path("figures/honeypot_tiers.json"),
    ]
    for p in candidates:
        if p.exists():
            with open(p) as f:
                return json.load(f)
    return None


def plot_honeypot_per_iter_heatmap(
    results: list[tuple[str, str]],
    out_dir: str = "figures/",
) -> Path:
    out_path = Path(out_dir) / "honeypot_per_iter_heatmap.png"
    sidecar_path = Path(out_dir) / "honeypot_per_iter_heatmap.json"
    out_path.parent.mkdir(parents=True, exist_ok=True)

    label, selfplay_dir = results[0]
    data = _load_tiers(selfplay_dir)
    if data is None:
        print("[honeypot_per_iter_heatmap] honeypot_tiers.json not found", file=sys.stderr)
        return out_path

    honeypots = data["honeypots"]
    n_iters = data.get("n_iterations", 8)
    iter_keys = [str(i) for i in range(n_iters)]

    # Sort: tier order, then by total_hits desc within tier
    def sort_key(h: dict) -> tuple:
        tier_rank = TIER_ORDER.index(h["tier"]) if h["tier"] in TIER_ORDER else len(TIER_ORDER)
        return (tier_rank, -h["total_hits"])

    honeypots_sorted = sorted(honeypots, key=sort_key)

    # Build matrix: rows = honeypots, cols = iters
    matrix = np.zeros((len(honeypots_sorted), n_iters), dtype=float)
    row_labels = []
    row_tiers = []
    for i, h in enumerate(honeypots_sorted):
        row_labels.append(h["id"].replace("column_access:", "col:").replace("table_access:", "tbl:").replace("salesorder_column_access:", "so_col:").replace("salesorderid:", "so_id:"))
        row_tiers.append(h["tier"])
        per_iter = h.get("per_iter_hits", {})
        for j, k in enumerate(iter_keys):
            matrix[i, j] = per_iter.get(k, 0)

    # Compute totals
    total_hits = matrix.sum()

    fig, ax = plt.subplots(figsize=(8.0, 0.32 * len(honeypots_sorted) + 1.5))

    im = ax.imshow(
        matrix,
        aspect="auto",
        cmap="Reds",
        interpolation="nearest",
        vmin=0,
        vmax=max(matrix.max(), 1.0),
    )

    # Annotate each cell with breach count
    for i in range(len(honeypots_sorted)):
        for j in range(n_iters):
            v = int(matrix[i, j])
            if v > 0:
                color = "white" if v > 0.6 * matrix.max() else "black"
                ax.text(j, i, str(v), ha="center", va="center", fontsize=7, color=color)

    # Tier-band background tinting via horizontal spans
    tier_runs: list[tuple[str, int, int]] = []
    cur_tier = row_tiers[0]
    start = 0
    for i, t in enumerate(row_tiers + [None]):
        if t != cur_tier:
            tier_runs.append((cur_tier, start, i - 1))
            if t is not None:
                cur_tier = t
                start = i
    for tier, s, e in tier_runs:
        ax.axhspan(s - 0.5, e + 0.5, color=TIER_BG_COLORS.get(tier, "#FFFFFF"), alpha=0.25, zorder=0)
        # Label band on left margin
        ax.text(
            -0.55,
            (s + e) / 2,
            TIER_LABELS.get(tier, tier),
            rotation=90,
            ha="center",
            va="center",
            fontsize=8,
            fontweight="bold",
            color={"pii_dominant": "#B71C1C", "harvestable": "#E65100", "rare": "#37474F"}.get(tier, "#000"),
        )

    ax.set_xticks(range(n_iters))
    ax.set_xticklabels(iter_keys)
    ax.set_yticks(range(len(honeypots_sorted)))
    ax.set_yticklabels(row_labels, fontsize=8)
    ax.set_xlabel("Co-evolved diagonal iter")
    ax.set_title(
        f"Per-honeypot breach counts × iter ({int(total_hits)} total hits, "
        f"canonical cross_eval, n=400 attack ep/cell)"
    )
    cb = fig.colorbar(im, ax=ax, fraction=0.025, pad=0.02)
    cb.set_label("Breach count per cell", fontsize=8)

    # Caption note
    top2_total = sum(h["total_hits"] for h in honeypots_sorted[:2])
    pct_top2 = top2_total / total_hits * 100
    fig.text(
        0.5,
        -0.02,
        f"Top-2 (phone + emailaddress) account for {pct_top2:.1f}% of all hits. "
        "Composition stable across all 8 iters → ceiling is target-set property, not co-evolution artifact.",
        ha="center",
        fontsize=8,
        style="italic",
    )

    fig.tight_layout()
    fig.savefig(out_path, dpi=150, bbox_inches="tight")
    plt.close(fig)

    # Sidecar
    sidecar = {
        "description": DESCRIPTION,
        "n_iterations": n_iters,
        "n_honeypots": len(honeypots_sorted),
        "total_hits": int(total_hits),
        "top2_share_pct": round(pct_top2, 2),
        "honeypots": [
            {
                "id": h["id"],
                "tier": h["tier"],
                "total_hits": h["total_hits"],
                "iters_with_hit": h["iters_with_hit"],
                "per_iter_hits": h.get("per_iter_hits", {}),
            }
            for h in honeypots_sorted
        ],
    }
    with open(sidecar_path, "w") as f:
        json.dump(sidecar, f, indent=2)

    print(f"[honeypot_per_iter_heatmap] saved {out_path}")
    return out_path


def main() -> None:
    p = argparse.ArgumentParser(description=DESCRIPTION)
    p.add_argument("--results", nargs="+", required=True)
    p.add_argument("--out-dir", default="figures/")
    args = p.parse_args()
    results = parse_results_arg(args.results)
    plot_honeypot_per_iter_heatmap(results, args.out_dir)


if __name__ == "__main__":
    main()
